dependencies:
  # - <organization/repo>@<version>
  # https://github.com/smartcontractkit/chainlink-brownie-contracts
  # These are the npm pkgs we imported in Solidity using the @ symbol
  #   but for brownie will download via github
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  # Once the chainlink-brownie-contracts are downloaded we can
  #   remap the @chainlink to the downloaded repository
compiler:
  solc:
    remappings:
      '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
networks:
  rinkeby:
    # https://docs.chain.link/docs/ethereum-addresses/
    eth_usd_price_feed_address: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    # https://docs.chain.link/docs/ethereum-addresses/
    eth_usd_price_feed_address:  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False 
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}